<template>
  <span
    class="taotu-svg-icon"
    aria-hidden="true"
    :class="{ 'taotu-svg-icon-filled': filled, 'taotu-svg-icon-spin': spinning }"
    :style="rootStyle"
  >
    <component
      :is="iconComponent"
      class="taotu-svg-icon-layer taotu-svg-icon-regular"
      :pack="regularPack"
      fill="currentColor"
      width="100%"
      height="100%"
      focusable="false"
    />
    <component
      v-if="stateful || filled"
      :is="iconComponent"
      class="taotu-svg-icon-layer taotu-svg-icon-fill"
      pack="filled"
      fill="currentColor"
      width="100%"
      height="100%"
      focusable="false"
    />
  </span>
</template>

<script setup>
import { computed } from 'vue'
import {
  AlertCircle,
  AlertOctagon,
  AlertTriangle,
  Announcement,
  Archive,
  ArchiveArrowUp,
  ArrowDownWideNarrow,
  ArrowLeft,
  ArrowToBottom,
  Bell,
  BellSlash,
  BracketCurly,
  ChartBarColumns,
  ChartWaterfall,
  Check,
  CheckCircle,
  CheckSquare,
  Checkbox,
  CheckboxChecked,
  CheckboxSquare,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  Circle,
  CircleDashed,
  ClipboardCode,
  Clock,
  Cloud,
  Code,
  CodeAlt,
  Cog,
  Cognition,
  Copy,
  CopyList,
  Dashboard,
  Database,
  DoorOpen,
  DotsHorizontal,
  Edit,
  Eye,
  EyeSlash,
  FolderOpen,
  FolderPlus,
  FolderUpArrow,
  Fullscreen,
  GalleryThumbnails,
  Github,
  Globe,
  Grid9,
  Heart,
  Home,
  Image,
  ImagePlus,
  ImageSparkle,
  Images,
  InfoCircle,
  Key,
  Link,
  ListUl,
  Lock,
  LockKeyhole,
  MenuFilter,
  Notification,
  PhotoAlbum,
  Plus,
  PlusCircle,
  PriceTag,
  RefreshCcw,
  RefreshCw,
  Rocket,
  Save,
  ScanDetail,
  ScanSearch,
  Search,
  SearchMinus,
  SearchPlus,
  SearchX,
  Send,
  Server,
  Shield,
  Trash,
  User,
  UserSquare,
  X,
  XCircle
} from '@boxicons/vue'

const props = defineProps({
  name: { type: String, default: 'image' },
  pack: { type: String, default: '' },
  filled: { type: Boolean, default: false },
  stateful: { type: Boolean, default: true },
  size: { type: [Number, String], default: '' },
  width: { type: [Number, String], default: '' },
  height: { type: [Number, String], default: '' }
})

const iconMap = {
  add: 'Plus',
  cancel: 'X',
  close: 'X',
  confirm: 'Check',
  copy: 'Copy',
  'copy-batch': 'CopyList',
  'copy-code': 'ClipboardCode',
  'copy-url': 'Link',
  delete: 'Trash',
  trash: 'Trash',
  edit: 'Edit',
  eye: 'Eye',
  'eye-off': 'EyeSlash',
  refresh: 'RefreshCw',
  restore: 'ArchiveArrowUp',
  save: 'Save',
  scan: 'ScanSearch',
  search: 'Search',
  settings: 'Cog',
  'more-actions-placeholder': 'DotsHorizontal',
  overview: 'Dashboard',
  dashboard: 'Dashboard',
  stats: 'ChartBarColumns',
  'image-management': 'Images',
  'content-management': 'Images',
  images: 'Images',
  image: 'Image',
  'album-management': 'PhotoAlbum',
  album: 'PhotoAlbum',
  albums: 'PhotoAlbum',
  'album-create': 'FolderPlus',
  'album-empty': 'PhotoAlbum',
  'create-plus': 'PlusCircle',
  'edit-info': 'Edit',
  'api-settings': 'CodeAlt',
  api: 'CodeAlt',
  backup: 'Archive',
  'cloud-sync': 'Cloud',
  'condition-tags': 'ScanDetail',
  'custom-paths': 'FolderOpen',
  database: 'Database',
  'gallery-settings': 'GalleryThumbnails',
  'model-management': 'Cognition',
  ops: 'Server',
  'site-config': 'Cog',
  'tag-settings': 'PriceTag',
  'tag-system': 'PriceTag',
  'tag-add': 'PriceTag',
  'tag-list': 'PriceTag',
  'user-permissions': 'Shield',
  users: 'User',
  user: 'User',
  'user-groups': 'UserSquare',
  'storage-strategy': 'Database',
  'return-front': 'Home',
  announcements: 'Announcement',
  'status-ok-placeholder': 'CheckCircle',
  'status-error-placeholder': 'XCircle',
  'toast-success': 'CheckCircle',
  'toast-warning': 'AlertCircle',
  'toast-error': 'XCircle',
  'toast-danger': 'XCircle',
  'toast-info': 'InfoCircle',
  info: 'InfoCircle',
  checkbox: 'Checkbox',
  'checkbox-checked': 'CheckboxChecked',
  'checkbox-square': 'CheckboxSquare',
  'grid-view': 'Grid9',
  grid: 'Grid9',
  'list-view': 'ListUl',
  list: 'ListUl',
  manage: 'Cog',
  'image-count': 'Images',
  'updated-time': 'Clock',
  views: 'Eye',
  'visibility-info': 'InfoCircle',
  private: 'LockKeyhole',
  public: 'Globe',
  'remove-image': 'Trash',
  'set-cover': 'ImagePlus',
  'pagination-next': 'ChevronRight',
  'pagination-prev': 'ChevronLeft',
  'album-list': 'PhotoAlbum',
  'random-album': 'PhotoAlbum',
  'embed-album': 'CodeAlt',
  'image-list': 'Images',
  'random-image': 'ImageSparkle',
  'embed-image': 'CodeAlt',
  'config-warning': 'AlertTriangle',
  curl: 'BracketCurly',
  'generated-url': 'Link',
  preview: 'Eye',
  'response-structure': 'Code',
  'send-request': 'Send',
  'account-security': 'Shield',
  'api-token': 'Key',
  password: 'LockKeyhole',
  profile: 'User',
  'private-tags': 'PriceTag',
  'recent-upload': 'Images',
  storage: 'Database',
  upgrade: 'Rocket',
  'backup-empty': 'Archive',
  'no-albums': 'PhotoAlbum',
  'no-data': 'Database',
  'no-images': 'Images',
  'no-models': 'Cognition',
  'registration-closed': 'Lock',
  'search-empty': 'SearchX',
  'upload-empty': 'FolderUpArrow',
  download: 'ArrowToBottom',
  'load-more': 'PlusCircle',
  filter: 'MenuFilter',
  'move-album': 'FolderUpArrow',
  'multi-select': 'CheckSquare',
  'my-gallery': 'Image',
  'public-gallery': 'Globe',
  sort: 'ArrowDownWideNarrow',
  'user-gallery': 'User',
  waterfall: 'ChartWaterfall',
  back: 'ArrowLeft',
  embed: 'CodeAlt',
  favorite: 'Heart',
  full: 'Fullscreen',
  fullscreen: 'Fullscreen',
  medium: 'Image',
  next: 'ChevronRight',
  previous: 'ChevronLeft',
  reset: 'RefreshCcw',
  thumbnail: 'GalleryThumbnails',
  'zoom-in': 'SearchPlus',
  'zoom-out': 'SearchMinus',
  admin: 'Shield',
  'chevron-down': 'ChevronDown',
  gallery: 'GalleryThumbnails',
  login: 'User',
  logout: 'DoorOpen',
  notification: 'Bell',
  'no-message': 'BellSlash',
  'system-message': 'Notification',
  upload: 'FolderUpArrow',
  disabled: 'Lock',
  enabled: 'CheckCircle',
  failure: 'XCircle',
  loading: 'CircleDashed',
  locked: 'LockKeyhole',
  'mutual-exclusive': 'AlertOctagon',
  pending: 'Clock',
  success: 'CheckCircle',
  warning: 'AlertTriangle',
  'review-approved': 'CheckCircle',
  'api-upload': 'CodeAlt',
  clear: 'X',
  'file-upload': 'FolderUpArrow',
  'github-host': 'Github',
  'imgbb-host': 'Image',
  progress: 'CircleDashed',
  'qiniu-host': 'Cloud',
  'smms-host': 'Cloud',
  'taotu-host': 'ImageSparkle',
  'tencent-cos-host': 'Cloud',
  'upload-cloud': 'FolderUpArrow',
  'url-upload': 'Link',
  selected: 'CheckCircle',
  unselected: 'Circle',
  '选中': 'CheckCircle',
  '未选中': 'Circle'
}

const iconComponents = {
  AlertCircle,
  AlertOctagon,
  AlertTriangle,
  Announcement,
  Archive,
  ArchiveArrowUp,
  ArrowDownWideNarrow,
  ArrowLeft,
  ArrowToBottom,
  Bell,
  BellSlash,
  BracketCurly,
  ChartBarColumns,
  ChartWaterfall,
  Check,
  CheckCircle,
  CheckSquare,
  Checkbox,
  CheckboxChecked,
  CheckboxSquare,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  Circle,
  CircleDashed,
  ClipboardCode,
  Clock,
  Cloud,
  Code,
  CodeAlt,
  Cog,
  Cognition,
  Copy,
  CopyList,
  Dashboard,
  Database,
  DoorOpen,
  DotsHorizontal,
  Edit,
  Eye,
  EyeSlash,
  FolderOpen,
  FolderPlus,
  FolderUpArrow,
  Fullscreen,
  GalleryThumbnails,
  Github,
  Globe,
  Grid9,
  Heart,
  Home,
  Image,
  ImagePlus,
  ImageSparkle,
  Images,
  InfoCircle,
  Key,
  Link,
  ListUl,
  Lock,
  LockKeyhole,
  MenuFilter,
  Notification,
  PhotoAlbum,
  Plus,
  PlusCircle,
  PriceTag,
  RefreshCcw,
  RefreshCw,
  Rocket,
  Save,
  ScanDetail,
  ScanSearch,
  Search,
  SearchMinus,
  SearchPlus,
  SearchX,
  Send,
  Server,
  Shield,
  Trash,
  User,
  UserSquare,
  X,
  XCircle
}

const normalizedName = computed(() => {
  const rawName = String(props.name || 'image')
  const fileName = rawName.split('/').pop()?.replace(/\.(png|svg|gif)$/i, '') || rawName
  return fileName.replace(/-\d+x\d+$/i, '').replace(/_128x128$/i, '').replace(/_64x64$/i, '')
})

const iconName = computed(() => iconMap[normalizedName.value] || iconMap[props.name] || 'Image')
const iconComponent = computed(() => iconComponents[iconName.value] || Image)
const filled = computed(() => props.filled || props.pack === 'filled')
const stateful = computed(() => props.stateful && !filled.value)
const spinning = computed(() => ['loading', 'progress'].includes(normalizedName.value))
const regularPack = computed(() => props.pack && props.pack !== 'filled' ? props.pack : 'regular')
const normalizeSize = (value) => typeof value === 'number' ? `${value}px` : value
const rootStyle = computed(() => {
  const width = normalizeSize(props.width || props.size || '')
  const height = normalizeSize(props.height || props.size || '')
  const style = {}
  if (width) style.width = width
  if (height) style.height = height
  return style
})
</script>
